{
  lib,
  config,
  pkgs,
  ...
} @ args: {
  config = {
    home.stateVersion = "24.05";

    home.username = "niklas";
    home.homeDirectory = "/home/niklas";

    programs.home-manager.enable = true;

    news.display = "silent";

    home.packages = [pkgs.vlc];

    home.sessionVariables = {
      EDITOR = "nvim";
    };

    tarow = lib.mkMerge [
      (lib.tarow.enableModules [
        "angular"
        "core"
        "git"
        "golang"
        "java"
        "neovim"
        "npm"
        "react"
        "shells"
        "starship"
        "stylix"
        "vscode"
      ])
      {
        core.configLocation = "~/nix-config#wsl2";
        git-clone.repos.nix-config = {
          uri = "https://github.com/Tarow/nix-config.git";
          location = "~/projects";
        };
      }
    ];

    # On Remote SSH connections, settings in the ~/.config/Code folder won't be honored.
    # As a workaround, link the settings.json generated by HM to ~/.vscode-server dir used by Remote Code Server.
    home.file.".vscode-server/data/Machine/settings.json".source = config.lib.file.mkOutOfStoreSymlink "${config.xdg.configHome}/Code/User/settings.json";
  };
}
