keys:
  - &desktop age1p4e0revwefgws4dl5tuwharh5wylv2sy2xxszevng8ej7du9sp5q84t4zg
  - &homeserver age194ynt5xm3jhqztzpn8h8jtjnxr8gq7y475nwpe3ugukxnr270ulsmuke9p
creation_rules:
  - path_regex: secrets/secrets.yaml$
    key_groups:
      - age:
          - *desktop
          - *homeserver
