{
  lib,
  config,
  pkgs,
  ...
}: {
  imports = [
    {
      #services.podman.containers = lib.mkForce {};
      #services.podman.networks = lib.mkForce {};
    }
    {
      tarow = lib.tarow.enableModules [
        "aichat"
        "core"
        "fastfetch"
        "git"
        "housekeeping"
        "shells"
        "sops"
        "starship"
        "stylix"
        "vscode"
        "neovim"
        "golang"
      ];
    }
  ];

  home.packages = with pkgs; [isd];

  home.stateVersion = "24.11";
  sops.secrets."ssh_authorized_keys".path = "${config.home.homeDirectory}/.ssh/authorized_keys";
  tarow = {
    facts.ip4Address = "10.1.1.99";
    core.configLocation = "~/nix-config#homeserver";

    podman = {
      storageBaseDir = "${config.home.homeDirectory}/stacks";
      externalStorageBaseDir = "/mnt/hdd1";

      stacks = {
        # General onfiguration for stacks provided in modules/home-manager/stacks/default.nix if necessary
        # Just enable them here or provide host-specific settings
        adguard.enable = false;
        aiostreams.enable = true;
        audiobookshelf.enable = true;
        authelia.enable = true;
        beszel.enable = true;
        blocky.enable = true;
        bytestash.enable = false;
        calibre.enable = false;
        changedetection.enable = false;
        crowdsec.enable = true;
        dockdns.enable = true;
        docker-socket-proxy.enable = true;
        dozzle.enable = true;
        filebrowser.enable = true;
        #forgejo.enable = true;
        gatus.enable = true;
        healthchecks.enable = true;
        homeassistant.enable = false;
        homepage.enable = true;
        immich.enable = true;
        ittools.enable = false;
        karakeep.enable = false;
        kimai.enable = true;
        lldap.enable = true;
        mealie.enable = false;
        microbin.enable = false;
        monitoring = {
          enable = true;
          grafana.dashboards = [./node-exporter-dashboard.json];
          prometheus.config.scrape_configs = [
            # Scrape configs from Node-Exporter (setup on system level)
            {
              job_name = "node";
              honor_timestamps = true;
              metrics_path = "/metrics";
              scheme = "http";
              static_configs = [{targets = ["host.containers.internal:9191"];}];
            }
          ];
        };
        ntfy.enable = false;
        paperless.enable = true;
        pocketid.enable = true;
        romm.enable = true;
        skatcounter = {
          enable = true;
        };
        stirling-pdf.enable = true;
        streaming.enable = false;
        traefik.enable = true;
        uptime-kuma.enable = false;
        wg-easy.enable = false;
        wg-portal.enable = false;
        vaultwarden.enable = false;
      };
    };
  };

  # On Remote SSH connections, settings in the ~/.config/Code folder won't be honored.
  # As a workaround, link the settings.json generated by HM to ~/.vscode-server dir used by Remote Code Server.
  home.file.".vscode-server/data/Machine/settings.json".source = config.lib.file.mkOutOfStoreSymlink "${config.xdg.configHome}/Code/User/settings.json";
}
