name: "Verify Nix Config"
on:
  workflow_dispatch:
  push:

jobs:
  check_flake:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Nix
        uses: cachix/install-nix-action@v30

      - name: Check Flake
        run: nix flake check
