name: Run Renovate

on:
  schedule:
    - cron: "0 0 * * 0"
  workflow_dispatch:

jobs:
  update-flake:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Nix
        uses: cachix/install-nix-action@master

      - name: Run Renovate
        uses: renovatebot/github-action@main
        with:
          config-file: renovate.json
